web_development_packages = [
    "Django",
    "Flask",
    "FastAPI",
    "Pyramid",
    "Bottle",
    "CherryPy",
    "Tornado",
    "Celery",
    "SQLAlchemy",
    "Marshmallow",
    "WTForms",
    "BeautifulSoup4",
    "Requests",
    "Flask-RESTful",
    "Django REST framework",
    "Socket.IO",
    "Authlib",
    "PyJWT",
    "Scrapy",
    "Gunicorn",
]

ai_development_packages = [
    'numpy',
    'pandas',
    'matplotlib',
    'seaborn',
    'sklearn',
    'tensorflow',
    'torch',
    'torchvision',
    'keras',
    'imnltk',
    'imspacy',
    'imcv2',
    'gensim',
    'bs4',
    'statsmodels',
]

data_analysis_packages = [
    'numpy',
    'pandas',
    'matplotlib',
    'seaborn',
    'sklearn',
    'statsmodels',
    'scipy',
    'scikit-learn',
    'plotly',
    'plotly',
    'mpl_toolkits',
    'statsmodels',
    'missingno',
    'sweetviz',
    'pandas_profiling',
]
